### ISSUE TITLE
Chưa add được 1 contact vào nhiều group

### ISSUE THREAD

**Issue by aesinhagao** [aesinhagao/name-card-management#10]

**Comment by Rin3105** [comment]
Đã chỉnh lại API AddContactsToGroups để có thể thêm:
1. 1 Contact đến 1 Group
2. 1 Contact đến nhiều Group
3. Nhiều Contact đến 1 Group
4. Nhiều Contact đến Nhiều Group

**Comment by Rin3105** [comment]
Tùng và Cường đã test chạy ổn định.
