### ISSUE TITLE
Xem lại Add group hiện tại đang thêm được dấu cách, add rỗng chưa báo lại người dùng, API vẫn chấp nhận cũng cần phải xem lại

### ISSUE THREAD

**Issue by aesinhagao** [aesinhagao/name-card-management#24]
https://user-images.githubusercontent.com/29669960/179514736-4aded3c6-7981-4da0-9b5e-b0a4d1c3d468.mp4

**Comment by luongquoccuong2103** [comment]
đã check trường hợp để rỗng tên nhóm hiện ra thông báo lỗi
